/**
 * RFC 2822 thread-key extraction for inbound reconciliation.
 *
 * The alias in Reply-To (`thread-{uuid}@replies.unusonic.com`) is the
 * AUTHORITATIVE thread resolution signal — it's generated by us and we
 * control it end-to-end. When alias match succeeds, the handler uses the
 * resolved `thread_id` directly and this module is never consulted.
 *
 * This module's thread-key is a SECONDARY reconciliation signal used
 * when:
 *   (a) The message arrived with no alias (e.g. forwarded manually, or a
 *       cold inbound on Phase 2's `hello@`) — today this doesn't happen
 *       in practice but the design doc reserves the pathway.
 *   (b) We need to backfill `provider_thread_key` on an existing alias-
 *       matched thread so header-based reconciliation can take over if
 *       the alias is ever dropped by a forwarding gateway.
 *
 * Cascade, in order of header reliability (Field Expert Q1, RFC 2822):
 *   1. In-Reply-To — the immediate parent message. Most reliable.
 *   2. References — the latest ancestor (LAST ID in the list), NOT the
 *      first. Why: Outlook, Thunderbird, and Apple Mail sometimes reorder
 *      or prepend to References when rebuilding the thread headers. The
 *      LAST entry is always the message the reply was composed against.
 *      The original bug (pre-2026-04-24) used `[0]` — the oldest ancestor
 *      — which is a valid root on first inbound but fails once the thread
 *      grows beyond one round-trip.
 *   3. Message-ID — the sender's own ID for THIS message. Only useful as
 *      a thread root when this is the first message in a future thread.
 *      Last-resort fallback.
 *
 * @module app/api/webhooks/postmark/__lib__/thread-key
 */

type HeaderLookup = (name: string) => string | null;

/**
 * Extract the best thread-reconciliation key from RFC 2822 headers.
 * Returns null if no header yields a usable key.
 */
export function extractThreadKey(getHeader: HeaderLookup): string | null {
  // 1. In-Reply-To — single Message-ID in angle brackets.
  const inReplyTo = getHeader('in-reply-to');
  const fromInReplyTo = firstMessageId(inReplyTo);
  if (fromInReplyTo) return fromInReplyTo;

  // 2. References — whitespace-separated list; LAST entry is the immediate
  //    parent on well-behaved clients (Field Expert Q1).
  const references = getHeader('references');
  const fromReferences = lastMessageId(references);
  if (fromReferences) return fromReferences;

  // 3. Message-ID — the sender's own id. Only useful as a thread root.
  const messageId = getHeader('message-id');
  const fromMessageId = firstMessageId(messageId);
  if (fromMessageId) return fromMessageId;

  return null;
}

/** Returns the FIRST bracketed Message-ID in a header value, or null. */
function firstMessageId(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const match = raw.match(/<([^<>\s]+)>/);
  if (match && match[1]) return match[1].trim();
  // Fallback for headers that ship without angle brackets (rare but real).
  const stripped = raw.trim();
  if (stripped && !/\s/.test(stripped)) return stripped.replace(/[<>]/g, '');
  return null;
}

/** Returns the LAST bracketed Message-ID in a header value, or null. */
function lastMessageId(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const matches = raw.match(/<([^<>\s]+)>/g);
  if (matches && matches.length > 0) {
    const last = matches[matches.length - 1];
    return last.replace(/[<>]/g, '').trim();
  }
  // No angle brackets — split by whitespace, take last non-empty token.
  const tokens = raw.trim().split(/\s+/).filter(Boolean);
  if (tokens.length === 0) return null;
  return tokens[tokens.length - 1].replace(/[<>]/g, '');
}
