/**
 * Portal Theme presets — 11 preset token definitions plus legacy slug aliases.
 *
 * Each preset is a complete PortalThemeTokens record. PRESET_ALIASES maps
 * legacy preset slugs to current ones for migration safety.
 *
 * @module shared/lib/portal-theme/presets
 */

import type { PortalThemePreset, PortalThemeTokens } from './types';


export const PRESETS: Record<PortalThemePreset, PortalThemeTokens> = {
  // ---------------------------------------------------------------------------
  // 1. Paper — warm white paper, near-black accent, general-purpose default.
  //    Character: heavy-stock stationery with dark ink. Quiet and competent.
  //    References: Muji stationery, Apple invoice receipts, Aesop product cards.
  // ---------------------------------------------------------------------------
  paper: {
    bg: 'oklch(0.985 0.003 80)',
    surface: 'oklch(0.97 0.003 80)',
    surfaceSubtle: 'oklch(0.94 0.003 80)',
    text: 'oklch(0.13 0.004 50)',
    textSecondary: 'oklch(0.45 0 0)',
    accent: 'oklch(0.20 0 0)',
    accentSubtle: 'oklch(0.95 0.003 80)',
    border: 'oklch(0.90 0.003 80)',
    borderSubtle: 'oklch(0.93 0.003 80)',
    fontHeading: 'var(--font-geist-sans), sans-serif',
    fontBody: 'var(--font-geist-sans), sans-serif',
    headingWeight: '300',
    headingTracking: '-0.02em',
    radius: '10px',
    borderWidth: '1px',
    shadow: '0 1px 2px oklch(0 0 0 / 0.04), 0 4px 16px -4px oklch(0 0 0 / 0.06)',
    shadowStrong: '0 1px 3px oklch(0 0 0 / 0.06), 0 8px 24px -6px oklch(0 0 0 / 0.10)',
    accentText: 'oklch(0.98 0 0)',
    heroAlign: 'center',
    btnRadius: '9999px',
    labelSize: '11px',
    labelTransform: 'uppercase',
    labelTracking: '0.08em',
    labelWeight: '600',
    cardPadding: '20px',
    gap: '20px',
    divider: 'none',
    heroPadding: '36px',
    heroTitleSize: '2rem',
    heroSurface: 'oklch(0.97 0.003 80)',
    totalScale: '1.5rem',
    contentMaxWidth: '48rem',
    itemLayout: 'card',
    sectionBgAlternate: 'false',
    sectionTrim: 'none',
    accentBand: 'none',
  },

  // ---------------------------------------------------------------------------
  // 2. Clean — pure white, pure black, zero radius, zero shadow. Typography
  //    and grid do all the work.
  //    Character: Swiss International Style. Disciplined, modern, no decoration.
  //    References: Josef Muller-Brockmann, Linear changelog, Braun manuals.
  // ---------------------------------------------------------------------------
  clean: {
    bg: 'oklch(1.0 0 0)',
    surface: 'oklch(0.98 0 0)',
    surfaceSubtle: 'oklch(0.96 0 0)',
    text: 'oklch(0.10 0 0)',
    textSecondary: 'oklch(0.50 0 0)',
    accent: 'oklch(0.10 0 0)',
    accentSubtle: 'oklch(0.96 0 0)',
    border: 'oklch(0.88 0 0)',
    borderSubtle: 'oklch(0.94 0 0)',
    fontHeading: 'var(--font-geist-sans), sans-serif',
    fontBody: 'var(--font-geist-sans), sans-serif',
    headingWeight: '500',
    headingTracking: '-0.03em',
    radius: '0px',
    borderWidth: '1px',
    shadow: 'none',
    shadowStrong: 'none',
    accentText: 'oklch(0.98 0 0)',
    heroAlign: 'left',
    btnRadius: '0px',
    labelSize: '12px',
    labelTransform: 'uppercase',
    labelTracking: '0.12em',
    labelWeight: '500',
    cardPadding: '16px',
    gap: '16px',
    divider: '1px solid oklch(0.88 0 0)',
    heroPadding: '24px',
    heroTitleSize: '1.75rem',
    heroSurface: 'oklch(0.98 0 0)',
    totalScale: '1.25rem',
    contentMaxWidth: '48rem',
    itemLayout: 'row',
    sectionBgAlternate: 'false',
    sectionTrim: 'straight',
    accentBand: 'top',
  },

  // ---------------------------------------------------------------------------
  // 3. Blackout — deep cool dark, technical precision, luminance-based elevation.
  //    Character: a proposal opened on a laptop backstage in a dim venue.
  //    References: Ableton Live, d&b audiotechnik, Tesla instrument cluster.
  // ---------------------------------------------------------------------------
  blackout: {
    bg: 'oklch(0.12 0.005 260)',
    surface: 'oklch(0.18 0.005 260)',
    surfaceSubtle: 'oklch(0.14 0.005 260)',
    text: 'oklch(0.92 0 0)',
    textSecondary: 'oklch(0.60 0 0)',
    accent: 'oklch(0.92 0 0)',
    accentSubtle: 'oklch(0.22 0.005 260)',
    border: 'oklch(0.25 0 0)',
    borderSubtle: 'oklch(0.20 0 0)',
    fontHeading: 'var(--font-geist-sans), sans-serif',
    fontBody: 'var(--font-geist-sans), sans-serif',
    headingWeight: '600',
    headingTracking: '-0.03em',
    radius: '6px',
    borderWidth: '1px',
    shadow: '0 0 0 1px oklch(1 0 0 / 0.04), 0 1px 4px oklch(0 0 0 / 0.3)',
    shadowStrong: '0 0 0 1px oklch(1 0 0 / 0.06), 0 2px 8px oklch(0 0 0 / 0.4), 0 0 24px -4px oklch(1 0 0 / 0.03)',
    accentText: 'oklch(0.12 0 0)',
    heroAlign: 'center',
    btnRadius: '6px',
    labelSize: '11px',
    labelTransform: 'uppercase',
    labelTracking: '0.10em',
    labelWeight: '500',
    cardPadding: '20px',
    gap: '16px',
    divider: '1px solid oklch(0.25 0 0)',
    heroPadding: '28px',
    heroTitleSize: '1.75rem',
    heroSurface: 'oklch(0.18 0.005 260)',
    totalScale: '1.25rem',
    contentMaxWidth: '48rem',
    itemLayout: 'row',
    sectionBgAlternate: 'false',
    sectionTrim: 'none',
    accentBand: 'none',
  },

  // ---------------------------------------------------------------------------
  // 4. Editorial — bold type, thick dividers, magazine spread feel.
  //    Character: a Monocle spread that happens to contain pricing.
  //    References: Bloomberg Businessweek, Acne Studios, Ssense editorial.
  // ---------------------------------------------------------------------------
  editorial: {
    bg: 'oklch(1.0 0 0)',
    surface: 'oklch(0.97 0.002 60)',
    surfaceSubtle: 'oklch(0.94 0.002 60)',
    text: 'oklch(0.0 0 0)',
    textSecondary: 'oklch(0.45 0 0)',
    accent: 'oklch(0.55 0.08 70)',
    accentSubtle: 'oklch(0.96 0.02 70)',
    border: 'oklch(0.90 0 0)',
    borderSubtle: 'oklch(0.94 0 0)',
    fontHeading: 'var(--font-geist-sans), sans-serif',
    fontBody: 'var(--font-geist-sans), sans-serif',
    headingWeight: '700',
    headingTracking: '-0.04em',
    radius: '2px',
    borderWidth: '1px',
    shadow: 'none',
    shadowStrong: 'none',
    accentText: 'oklch(1.0 0 0)',
    heroAlign: 'left',
    btnRadius: '2px',
    labelSize: '14px',
    labelTransform: 'uppercase',
    labelTracking: '0.15em',
    labelWeight: '700',
    cardPadding: '24px',
    gap: '24px',
    divider: '2px solid oklch(0 0 0)',
    heroPadding: '32px',
    heroTitleSize: '2.25rem',
    heroSurface: 'oklch(0.97 0.002 60)',
    totalScale: '1.25rem',
    contentMaxWidth: '52rem',
    itemLayout: 'minimal',
    sectionBgAlternate: 'true',
    sectionTrim: 'straight',
    accentBand: 'bottom',
  },

  // ---------------------------------------------------------------------------
  // 5. Civic — clean, trustworthy, warm but not luxurious.
  //    Character: a well-designed annual report. Credible, warm, clear.
  //    Blue-gray tint signals trust and institution. Muted teal accent.
  //    References: university press materials, nonprofit annual reports.
  // ---------------------------------------------------------------------------
  civic: {
    bg: 'oklch(0.98 0.005 85)',
    surface: 'oklch(0.96 0.008 240)',
    surfaceSubtle: 'oklch(0.93 0.006 240)',
    text: 'oklch(0.18 0.008 50)',
    textSecondary: 'oklch(0.48 0.005 50)',
    accent: 'oklch(0.50 0.10 220)',
    accentSubtle: 'oklch(0.94 0.02 220)',
    border: 'oklch(0.90 0.005 240)',
    borderSubtle: 'oklch(0.93 0.003 240)',
    fontHeading: 'var(--font-geist-sans), sans-serif',
    fontBody: 'var(--font-geist-sans), sans-serif',
    headingWeight: '500',
    headingTracking: '-0.01em',
    radius: '8px',
    borderWidth: '1px',
    shadow: '0 1px 3px oklch(0.18 0.01 240 / 0.05), 0 4px 12px -4px oklch(0.18 0.01 240 / 0.06)',
    shadowStrong: '0 2px 6px oklch(0.18 0.01 240 / 0.06), 0 8px 20px -6px oklch(0.18 0.01 240 / 0.08)',
    accentText: 'oklch(1.0 0 0)',
    heroAlign: 'center',
    btnRadius: '8px',
    labelSize: '12px',
    labelTransform: 'none',
    labelTracking: '0em',
    labelWeight: '500',
    cardPadding: '24px',
    gap: '20px',
    divider: 'none',
    heroPadding: '32px',
    heroTitleSize: '1.875rem',
    heroSurface: 'oklch(0.96 0.008 240)',
    totalScale: '1.375rem',
    contentMaxWidth: '48rem',
    itemLayout: 'card',
    sectionBgAlternate: 'false',
    sectionTrim: 'none',
    accentBand: 'none',
  },

  // ---------------------------------------------------------------------------
  // 6. Linen — serif headings, cream tones, luxury stationery.
  //    Character: a handwritten note on heavy cream paper. Warm and personal.
  //    References: Smythson stationery, Cereal magazine, The Ned hotel menus.
  // ---------------------------------------------------------------------------
  linen: {
    bg: 'oklch(0.96 0.012 70)',
    surface: 'oklch(0.99 0.006 70)',
    surfaceSubtle: 'oklch(0.93 0.012 70)',
    text: 'oklch(0.20 0.02 50)',
    textSecondary: 'oklch(0.50 0.02 50)',
    accent: 'oklch(0.50 0.12 30)',
    accentSubtle: 'oklch(0.94 0.03 30)',
    border: 'oklch(0.88 0.02 70)',
    borderSubtle: 'oklch(0.92 0.01 70)',
    fontHeading: 'var(--font-playfair), serif',
    fontBody: 'var(--font-geist-sans), sans-serif',
    headingWeight: '400',
    headingTracking: '0em',
    radius: '12px',
    borderWidth: '1px',
    shadow: '0 2px 12px oklch(0.20 0.02 50 / 0.06)',
    shadowStrong: '0 4px 20px oklch(0.20 0.02 50 / 0.08), 0 12px 40px -8px oklch(0.20 0.02 50 / 0.06)',
    accentText: 'oklch(1.0 0 0)',
    heroAlign: 'center',
    btnRadius: '9999px',
    labelSize: '11px',
    labelTransform: 'none',
    labelTracking: '0.02em',
    labelWeight: '400',
    cardPadding: '28px',
    gap: '24px',
    divider: 'none',
    heroPadding: '48px',
    heroTitleSize: '2.75rem',
    heroSurface: 'oklch(0.99 0.006 70)',
    totalScale: '2rem',
    contentMaxWidth: '42rem',
    itemLayout: 'card',
    sectionBgAlternate: 'false',
    sectionTrim: 'wave',
    accentBand: 'none',
  },

  // ---------------------------------------------------------------------------
  // 7. Poster — 2px black borders, hard offset shadows, vivid accent.
  //    Character: a gig flyer designed by a graphic designer. Bold and stamped.
  //    References: Virgil Abloh / Off-White, Rough Trade, Figma marketing.
  // ---------------------------------------------------------------------------
  poster: {
    bg: 'oklch(0.97 0.01 90)',
    surface: 'oklch(1.0 0 0)',
    surfaceSubtle: 'oklch(0.94 0.01 90)',
    text: 'oklch(0.0 0 0)',
    textSecondary: 'oklch(0.35 0 0)',
    accent: 'oklch(0.65 0.25 30)',
    accentSubtle: 'oklch(0.95 0.05 30)',
    border: 'oklch(0.0 0 0)',
    borderSubtle: 'oklch(0.0 0 0 / 0.15)',
    fontHeading: 'var(--font-space-grotesk), sans-serif',
    fontBody: 'var(--font-geist-sans), sans-serif',
    headingWeight: '700',
    headingTracking: '-0.01em',
    radius: '4px',
    borderWidth: '2px',
    shadow: '4px 4px 0 oklch(0 0 0 / 0.08)',
    shadowStrong: '6px 6px 0 oklch(0 0 0 / 0.12)',
    accentText: 'oklch(1.0 0 0)',
    heroAlign: 'left',
    btnRadius: '4px',
    labelSize: '13px',
    labelTransform: 'uppercase',
    labelTracking: '0.06em',
    labelWeight: '700',
    cardPadding: '20px',
    gap: '16px',
    divider: '2px solid oklch(0 0 0)',
    heroPadding: '28px',
    heroTitleSize: '2.25rem',
    heroSurface: 'oklch(1.0 0 0)',
    totalScale: '1.5rem',
    contentMaxWidth: '52rem',
    itemLayout: 'card',
    sectionBgAlternate: 'true',
    sectionTrim: 'angle',
    accentBand: 'top',
  },

  // ---------------------------------------------------------------------------
  // 8. Terminal — monospace headings, green-gray palette, compact and data-dense.
  //    Character: a vintage terminal crossed with modern design.
  //    References: Bloomberg Terminal, TE OP-1, Braun ET66, VT100.
  // ---------------------------------------------------------------------------
  terminal: {
    bg: 'oklch(0.95 0.005 100)',
    surface: 'oklch(0.98 0.003 100)',
    surfaceSubtle: 'oklch(0.92 0.005 100)',
    text: 'oklch(0.18 0.01 100)',
    textSecondary: 'oklch(0.48 0.01 100)',
    accent: 'oklch(0.55 0.10 160)',
    accentSubtle: 'oklch(0.93 0.02 160)',
    border: 'oklch(0.86 0.005 100)',
    borderSubtle: 'oklch(0.90 0.005 100)',
    fontHeading: 'var(--font-jetbrains), monospace',
    fontBody: 'var(--font-geist-sans), sans-serif',
    headingWeight: '400',
    headingTracking: '0em',
    radius: '6px',
    borderWidth: '1px',
    shadow: '0 1px 3px oklch(0.18 0.01 100 / 0.06), 0 4px 12px -4px oklch(0.18 0.01 100 / 0.08)',
    shadowStrong: '0 2px 6px oklch(0.18 0.01 100 / 0.08), 0 8px 20px -6px oklch(0.18 0.01 100 / 0.10)',
    accentText: 'oklch(1.0 0 0)',
    heroAlign: 'left',
    btnRadius: '4px',
    labelSize: '11px',
    labelTransform: 'uppercase',
    labelTracking: '0.10em',
    labelWeight: '400',
    cardPadding: '16px',
    gap: '12px',
    divider: '1px solid oklch(0.86 0.005 100)',
    heroPadding: '20px',
    heroTitleSize: '1.5rem',
    heroSurface: 'oklch(0.98 0.003 100)',
    totalScale: '1.125rem',
    contentMaxWidth: '52rem',
    itemLayout: 'row',
    sectionBgAlternate: 'false',
    sectionTrim: 'dots',
    accentBand: 'none',
  },

  // ---------------------------------------------------------------------------
  // 9. Marquee — dark warm charcoal, serif headings, gold accent, theatrical.
  //    Character: a playbill for a grand theater. The curtain is about to go up.
  //    References: Lincoln Center signage, Criterion Collection, Cartier at night.
  // ---------------------------------------------------------------------------
  marquee: {
    bg: 'oklch(0.14 0.01 50)',
    surface: 'oklch(0.20 0.01 50)',
    surfaceSubtle: 'oklch(0.16 0.008 50)',
    text: 'oklch(0.90 0.005 70)',
    textSecondary: 'oklch(0.58 0.005 50)',
    accent: 'oklch(0.72 0.12 85)',
    accentSubtle: 'oklch(0.22 0.02 85)',
    border: 'oklch(0.28 0.01 50)',
    borderSubtle: 'oklch(0.22 0.005 50)',
    fontHeading: 'var(--font-playfair), serif',
    fontBody: 'var(--font-geist-sans), sans-serif',
    headingWeight: '700',
    headingTracking: '-0.01em',
    radius: '8px',
    borderWidth: '1px',
    shadow: '0 2px 8px oklch(0 0 0 / 0.3), 0 0 1px oklch(0.72 0.12 85 / 0.08)',
    shadowStrong: '0 4px 16px oklch(0 0 0 / 0.4), 0 0 2px oklch(0.72 0.12 85 / 0.12)',
    accentText: 'oklch(0.12 0.01 50)',
    heroAlign: 'center',
    btnRadius: '4px',
    labelSize: '11px',
    labelTransform: 'uppercase',
    labelTracking: '0.10em',
    labelWeight: '600',
    cardPadding: '24px',
    gap: '20px',
    divider: 'none',
    heroPadding: '40px',
    heroTitleSize: '2.5rem',
    heroSurface: 'oklch(0.20 0.01 50)',
    totalScale: '1.75rem',
    contentMaxWidth: '46rem',
    itemLayout: 'minimal',
    sectionBgAlternate: 'false',
    sectionTrim: 'none',
    accentBand: 'bottom',
  },

  // ---------------------------------------------------------------------------
  // 10. Broadcast — ultra-bold, ultra-compact, high-energy. Everything is taut
  //     and forward-leaning.
  //     Character: a dashboard at launch speed. F1 timing screen meets Nike SNKRS.
  //     References: Nike SNKRS, Stripe Dashboard density, F1 race timing, Figma UI3.
  // ---------------------------------------------------------------------------
  broadcast: {
    bg: 'oklch(1.0 0 0)',
    surface: 'oklch(0.97 0 0)',
    surfaceSubtle: 'oklch(0.94 0 0)',
    text: 'oklch(0.05 0 0)',
    textSecondary: 'oklch(0.40 0 0)',
    accent: 'oklch(0.15 0 0)',
    accentSubtle: 'oklch(0.94 0 0)',
    border: 'oklch(0.82 0 0)',
    borderSubtle: 'oklch(0.90 0 0)',
    fontHeading: 'var(--font-geist-sans), sans-serif',
    fontBody: 'var(--font-geist-sans), sans-serif',
    headingWeight: '800',
    headingTracking: '-0.04em',
    radius: '2px',
    borderWidth: '1.5px',
    shadow: '0 1px 2px oklch(0 0 0 / 0.06)',
    shadowStrong: '0 2px 6px oklch(0 0 0 / 0.10)',
    accentText: 'oklch(0.98 0 0)',
    heroAlign: 'left',
    btnRadius: '2px',
    labelSize: '10px',
    labelTransform: 'uppercase',
    labelTracking: '0.14em',
    labelWeight: '800',
    cardPadding: '14px',
    gap: '10px',
    divider: '1.5px solid oklch(0.82 0 0)',
    heroPadding: '20px',
    heroTitleSize: '1.625rem',
    heroSurface: 'oklch(0.97 0 0)',
    totalScale: '1.125rem',
    contentMaxWidth: '56rem',
    itemLayout: 'row',
    sectionBgAlternate: 'true',
    sectionTrim: 'straight',
    accentBand: 'none',
  },

  // ---------------------------------------------------------------------------
  // 11. Gallery — ultra-light weight, vast spacing, maximum restraint.
  //     Character: walking through a white-walled art gallery. Three items in
  //     a thousand square feet.
  //     References: White Cube gallery, Cereal magazine, Jil Sander campaigns.
  // ---------------------------------------------------------------------------
  gallery: {
    bg: 'oklch(0.99 0.002 240)',
    surface: 'oklch(0.97 0.002 240)',
    surfaceSubtle: 'oklch(0.95 0.002 240)',
    text: 'oklch(0.15 0 0)',
    textSecondary: 'oklch(0.55 0 0)',
    accent: 'oklch(0.30 0 0)',
    accentSubtle: 'oklch(0.96 0.002 240)',
    border: 'oklch(0.94 0 0)',
    borderSubtle: 'oklch(0.96 0 0)',
    fontHeading: 'var(--font-geist-sans), sans-serif',
    fontBody: 'var(--font-geist-sans), sans-serif',
    headingWeight: '250',
    headingTracking: '0.02em',
    radius: '16px',
    borderWidth: '0px',
    shadow: '0 1px 4px oklch(0 0 0 / 0.03), 0 8px 32px -8px oklch(0 0 0 / 0.05)',
    shadowStrong: '0 2px 8px oklch(0 0 0 / 0.04), 0 16px 48px -12px oklch(0 0 0 / 0.07)',
    accentText: 'oklch(0.98 0 0)',
    heroAlign: 'center',
    btnRadius: '9999px',
    labelSize: '12px',
    labelTransform: 'none',
    labelTracking: '0.06em',
    labelWeight: '300',
    cardPadding: '36px',
    gap: '36px',
    divider: 'none',
    heroPadding: '56px',
    heroTitleSize: '2.75rem',
    heroSurface: 'oklch(0.97 0.002 240)',
    totalScale: '2rem',
    contentMaxWidth: '40rem',
    itemLayout: 'minimal',
    sectionBgAlternate: 'false',
    sectionTrim: 'none',
    accentBand: 'none',
  },

  // ---------------------------------------------------------------------------
  // Custom — falls back to Paper, overridden by portal_theme_config.
  // ---------------------------------------------------------------------------
  custom: {
    bg: 'oklch(0.985 0.003 80)',
    surface: 'oklch(0.97 0.003 80)',
    surfaceSubtle: 'oklch(0.94 0.003 80)',
    text: 'oklch(0.13 0.004 50)',
    textSecondary: 'oklch(0.45 0 0)',
    accent: 'oklch(0.20 0 0)',
    accentSubtle: 'oklch(0.95 0.003 80)',
    border: 'oklch(0.90 0.003 80)',
    borderSubtle: 'oklch(0.93 0.003 80)',
    fontHeading: 'var(--font-geist-sans), sans-serif',
    fontBody: 'var(--font-geist-sans), sans-serif',
    headingWeight: '300',
    headingTracking: '-0.02em',
    radius: '10px',
    borderWidth: '1px',
    shadow: '0 1px 2px oklch(0 0 0 / 0.04), 0 4px 16px -4px oklch(0 0 0 / 0.06)',
    shadowStrong: '0 1px 3px oklch(0 0 0 / 0.06), 0 8px 24px -6px oklch(0 0 0 / 0.10)',
    accentText: 'oklch(0.98 0 0)',
    heroAlign: 'center',
    btnRadius: '9999px',
    labelSize: '11px',
    labelTransform: 'uppercase',
    labelTracking: '0.08em',
    labelWeight: '600',
    cardPadding: '20px',
    gap: '20px',
    divider: 'none',
    heroPadding: '36px',
    heroTitleSize: '2rem',
    heroSurface: 'oklch(0.97 0.003 80)',
    totalScale: '1.5rem',
    contentMaxWidth: '48rem',
    itemLayout: 'card',
    sectionBgAlternate: 'false',
    sectionTrim: 'none',
    accentBand: 'none',
  },
};

// =============================================================================
// Migration alias map — old slug → new slug
// Ensures workspaces using legacy preset names continue to resolve correctly
// after the rename. No DB migration required.
// =============================================================================

export const PRESET_ALIASES: Record<string, PortalThemePreset> = {
  'default': 'paper',
  'minimalist': 'clean',
  'dark-stage': 'blackout',
  // 'editorial' unchanged
  // 'civic' unchanged
  'tactile-warm': 'linen',
  'neo-brutalist': 'poster',
  'retro-future': 'terminal',
};
