-- Bridge: per-launch nonce handshake columns.
--
-- Closes the last hole in the loopback API. After Commit 5, the loopback API
-- rejects DNS rebinding (Host header check) and refuses cross-origin reads
-- from non-allowlisted sites (explicit CORS origins). But any caller in the
-- allowlist — including a future Vercel preview branch or a browser extension
-- that bypasses CORS entirely — can still trigger sync endpoints
-- unauthenticated.
--
-- The per-launch nonce closes this. On Bridge startup the companion app
-- generates a 32-byte random token, stores it in memory only, and POSTs it to
-- `/api/bridge/local-session` using its opaque device token as auth. The web
-- server persists it here. When the portal needs to call the loopback API, it
-- first fetches the nonce via a server action (Supabase session auth — the
-- row is RLS-protected by user_id), then includes `Authorization: Bearer
-- {nonce}` on the loopback request. Bridge validates against its in-memory
-- copy.
--
-- Security: a Bridge restart invalidates the nonce (in-memory only on the
-- client). A DB dump that leaks nonces is low-impact because the nonce is
-- only useful while that specific Bridge instance is still running and
-- reachable on loopback.

ALTER TABLE public.bridge_device_tokens
  ADD COLUMN IF NOT EXISTS local_session_nonce      text,
  ADD COLUMN IF NOT EXISTS local_session_updated_at timestamptz;

COMMENT ON COLUMN public.bridge_device_tokens.local_session_nonce IS
  'Per-launch nonce generated by the Bridge companion app on startup and '
  'posted to /api/bridge/local-session. Used by the portal to authenticate '
  'loopback API calls to 127.0.0.1:19433. Rotates on every Bridge restart.';

COMMENT ON COLUMN public.bridge_device_tokens.local_session_updated_at IS
  'When the Bridge companion last posted a fresh nonce. Used to pick the most '
  'recent device when multiple are paired.';
