-- Bridge: migrate from JWT-signed device tokens to opaque random tokens,
-- and upgrade pairing code from 6-char uppercase hex (~24 bits) to
-- 8-char Crockford base32 (~40 bits).
--
-- Why opaque tokens: GitHub PATs, Stripe restricted keys, Slack bot tokens,
-- and AWS IAM access keys are all opaque. JWTs buy nothing when you already
-- DB-lookup for revocation, and reusing SUPABASE_JWT_SECRET was a blast-radius
-- violation. New tokens are `unb_live_` + 32 bytes base64url (~192 bits),
-- SHA-256 hashed in the existing `token_hash` column.
--
-- Why Crockford base32: the old code was `upper(substr(gen_random_uuid(), 1, 6))`
-- which yielded uppercase hex (0-9A-F only), so 16^6 ≈ 24 bits. 8-char Crockford
-- base32 gives 32^8 ≈ 40 bits from a 32-character alphabet that excludes
-- visually confusable characters (I, L, O, U). Matches RFC 8628, GitHub device
-- flow, and Trakt's device pairing code format.
--
-- Breaking change: any existing JWT-format tokens in `bridge_device_tokens`
-- will stop verifying because the new verification code requires the
-- `unb_live_` prefix. We clear both tables so there's no ambiguity. Pre-prod
-- only — no customer data exists yet.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Clear JWT-era data. Any paired Bridge installs will need to re-pair.
TRUNCATE TABLE public.bridge_device_tokens CASCADE;
TRUNCATE TABLE public.bridge_pairing_codes CASCADE;

COMMENT ON COLUMN public.bridge_device_tokens.token_hash IS
  'SHA-256 hex of the opaque device token. Tokens are generated by the web API '
  'as `unb_live_` + 32 random bytes (base64url) and never stored in plaintext.';

-- Replace the pairing code generator with Crockford base32.
CREATE OR REPLACE FUNCTION public.generate_bridge_pairing_code(
  p_user_id uuid,
  p_person_entity_id uuid
) RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  -- Crockford base32: 32 chars, excludes I, L, O, U for readability.
  v_alphabet constant text := '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
  v_code text := '';
  v_bytes bytea;
  i int;
BEGIN
  -- Invalidate any existing unused codes for this user (single active code).
  UPDATE public.bridge_pairing_codes
  SET expires_at = now()
  WHERE user_id = p_user_id
    AND consumed_at IS NULL
    AND expires_at > now();

  -- 8 random bytes → 8 base32 chars. Bias-free because 256 mod 32 = 0.
  v_bytes := gen_random_bytes(8);
  FOR i IN 0..7 LOOP
    v_code := v_code || substr(v_alphabet, (get_byte(v_bytes, i) % 32) + 1, 1);
  END LOOP;

  INSERT INTO public.bridge_pairing_codes (user_id, person_entity_id, code, expires_at)
  VALUES (p_user_id, p_person_entity_id, v_code, now() + interval '5 minutes');

  RETURN v_code;
END;
$$;

GRANT EXECUTE ON FUNCTION public.generate_bridge_pairing_code(uuid, uuid) TO authenticated;
